### ISSUE TITLE
Sprites error Pokémon silver 

### ISSUE THREAD

**Issue by Reideldm** [risingPhil/PokeMe64#10]
Using Pokemon Silver when entering the events at the New York Pokemon Center the sprites are displayed incorrectly and when exploring the list an error occurs. I use an original Pokemon Silver and an ed64p
![IMG_20241007_201111](https://github.com/user-attachments/assets/af53294b-0039-46c2-9ecb-82b5f0815389)
![Uploading IMG_20241007_201152.jpg…]()

**Comment by Reideldm** [comment]
I tried with red blue yellow gold without problems the error only occurs with silver

**Comment by risingPhil** [comment]
Hi, thank you for logging the issue.

There are only 2 games I don't personally own right now: Silver and Red. Luckily I'll be able to debug this in ares emulator, so no worries there.

But it's weird that there would be a difference in silver. I wouldn't expect there to be a binary position shift there at all.

Are you using an international/english version? Or is your copy of silver a different localization? (french, spanish, german, japanese, italian, korean, chinese, hindi, thai?)

**Comment by Reideldm** [comment]
My version is international English and it is an original, and by the
way I tell you friend, the work

you are doing with pokeme64 is a love letter for all the fans of the
first and second generation so kudos to you

**Comment by risingPhil** [comment]
Thank you for the info and the praise! :) And thank you for using PokeMe64 in the first place. I'm honored that my project is useful to some!

I'll look into this issue as soon as I can. I might even consider creating a bugfix release when I find the fix. But right now I can't give an ETA because I don't know what the problem is yet.

**Comment by Reideldm** [comment]
Don't worry, man, one step after another, I will wait patiently. I
wish you the best of luck in finding the isue and that you can improve
your project, which is wonderful. I am lucky and I am honored to be
able to use it.

**Comment by risingPhil** [comment]
I have fixed this bug with https://github.com/risingPhil/libpokemegb/pull/1 and https://github.com/risingPhil/PokeMe64/pull/11

I'll create a bugfix release.

**Comment by risingPhil** [comment]
Here is the new bugfix release: https://github.com/risingPhil/PokeMe64/releases/tag/v0.2.1

**Comment by Reideldm** [comment]
Looks great!
https://www.wikidex.net/wiki/Lista_de_eventos_de_la_primera_generaci%C3%B3n.
    Wonderful, I already tried it, it works as expected, I was looking at
this website and it seems that there are many more generation 1 pokemon
apart from the mews, most of which were distributed in Japan around 1997.
Maybe you can take a look at it later and evaluate if it is worth it ok
have a nice day good job

**Comment by risingPhil** [comment]
Thank you for the feedback!

As far as I know, I'm only missing the japanese ones. Your link doesn't seem to disprove that. And this has kinda been a conscious decision because I don't support the japanese localization (yet?). 

At the time I thought that having these event pokémon inside the international releases would perhaps feel out of place.

But I'm honestly open to add them if people would like to have them. So I will consider this for a later time. Thanks for the suggestion!

**Comment by Reideldm** [comment]
Totally understand!

**Comment by risingPhil** [comment]
Allright. Anyway, thanks a lot for your contribution by creating this issue ticket and your idea! It has already improved the project :)

And thanks for using PokeMe64!

**Comment by Reideldm** [comment]
You're welcome!

**Comment by risingPhil** [comment]
Hi, I randomly ended up looking at this ticket again. 

I just wanted to say -in case you were not aware- that the new v0.3 release now DOES have the Japanese distribution event pokémon.

Anyway, enjoy!

**Comment by Reideldm** [comment]
Thanks You bro
